### ISSUE TITLE
Any way to roll back Chrome to prior (58)?

### ISSUE THREAD

**Issue by djabraham** [ChromeDevTools/devtools-frontend#27]
Our automated tests are frequently broken by updates to Chrome, especially the dev tools. I just saw this after the update to 59. Based on some Internet queries, others have been experiencing issues as well. 

    [8764:9096:0705/091216.837:ERROR:CONSOLE(1570)] "Uncaught TypeError: uiSourceCodeFrame.attachInfobars is not a function", source: chrome-devtools://devtools/bundled/sources/sources_module.js (1570)

Is there any easy way to revert Chrome when necessary, to avoid significant delays for those who depend on integrations? The version of chromedriver we are using is supposed to function through v60.

When I navigate to ```chrome-devtools://devtools/bundled/sources/sources_module.js```, I see references to attachInfobars, but I do not see any source for it. I already uninstalled and reinstalled Chrome.
